Repository boostorg/geometry, pull requests merged in 2018-11, with the labels that each got.

#522 Support python3 in building documentation
  doc/make_qbk.py
Labels: bug

#525 Add compile-only tests verifying headers are self-contained
  test/Jamfile.v2
  test/self_contained_headers/Jamfile
  test/self_contained_headers/main.cpp
Labels: enhancement, tests

#529 Run headers tests only on demand
  test/Jamfile.v2
Labels: tests

#530 Several tweaks for tests of self contained headers.
  extensions/test/headers/Jamfile
  test/headers/Jamfile
  test/headers/main.cpp
Labels: tests

#532 Documentation fixes.
  doc/doxy/Doxyfile
  doc/doxy/doxygen_input/groups/groups.hpp
  doc/html/index.html
  doc/make_qbk.py
  doc/reference.qbk
  doc/release_notes.qbk
  include/boost/geometry/algorithms/detail/distance/interface.hpp
  include/boost/geometry/algorithms/discrete_frechet_distance.hpp
  include/boost/geometry/algorithms/discrete_hausdorff_distance.hpp
  include/boost/geometry/io/dsv/write.hpp
Labels: documentation

#534 Fix minor issues in documentation and release notes
  doc/html/index.html
  doc/imports.qbk
  doc/make_qbk.py
  doc/release_notes.qbk
Labels: documentation
