Repository boostorg/geometry, pull requests merged in 2019-02, with the labels that each got.

#551 Feature/remove rescaling preparations
  include/boost/geometry/algorithms/detail/overlay/enrich_intersection_points.hpp
  include/boost/geometry/algorithms/detail/overlay/get_turn_info.hpp
  include/boost/geometry/algorithms/detail/overlay/get_turn_info_helpers.hpp
  include/boost/geometry/algorithms/detail/overlay/traversal.hpp
  include/boost/geometry/algorithms/detail/overlay/traversal_ring_creator.hpp
  test/algorithms/overlay/multi_overlay_cases.hpp
  test/algorithms/overlay/overlay_cases.hpp
  test/algorithms/set_operations/difference/difference.cpp
  test/algorithms/set_operations/difference/difference_multi.cpp
  test/algorithms/set_operations/difference/test_difference.hpp
  test/algorithms/set_operations/intersection/intersection.cpp
  test/algorithms/set_operations/intersection/intersection_multi.cpp
  test/algorithms/set_operations/intersection/test_intersection.hpp
  test/algorithms/set_operations/union/union.cpp
Labels: enhancement

#553 Pass spheroid correctly in geographic comparable strategies
  doc/release_notes.qbk
  include/boost/geometry/strategies/geographic/distance_cross_track.hpp
  include/boost/geometry/strategies/geographic/distance_cross_track_box_box.hpp
  include/boost/geometry/strategies/geographic/distance_cross_track_point_box.hpp
  test/algorithms/distance/distance_geo_pl_l.cpp
  test/algorithms/distance/distance_se_geo_ar_ar.cpp
  test/algorithms/distance/distance_se_geo_pl_ar.cpp
  test/algorithms/distance/distance_se_geo_pl_pl.cpp
Labels: bug

#552 [overlay] Fix unused parameters warnings.
  include/boost/geometry/algorithms/detail/overlay/get_turn_info.hpp
Labels: warning

#546 Feature/buffer point geographic
  doc/html/index.html
  doc/imports.qbk
  doc/make_qbk.py
  doc/quickref.xml
  doc/reference.qbk
  doc/reference/algorithms/buffer.qbk
  doc/reference/algorithms/buffer_with_strategies.qbk
  doc/src/examples/strategies/Jamfile.v2
  doc/src/examples/strategies/buffer_geographic_point_circle.cpp
  include/boost/geometry/algorithms/detail/buffer/buffer_policies.hpp
  include/boost/geometry/algorithms/detail/buffer/buffered_piece_collection.hpp
  include/boost/geometry/algorithms/detail/buffer/get_piece_turns.hpp
  include/boost/geometry/algorithms/detail/buffer/turn_in_piece_visitor.hpp
  include/boost/geometry/algorithms/detail/overlay/assign_parents.hpp
  include/boost/geometry/algorithms/detail/overlay/select_rings.hpp
  include/boost/geometry/strategies/cartesian/buffer_point_circle.hpp
  include/boost/geometry/strategies/cartesian/buffer_point_square.hpp
  include/boost/geometry/strategies/geographic/buffer_point_circle.hpp
  include/boost/geometry/strategies/strategies.hpp
  test/algorithms/buffer/Jamfile.v2
  test/algorithms/buffer/buffer.cpp
  test/algorithms/buffer/buffer_countries.cpp
  test/algorithms/buffer/buffer_linestring.cpp
  test/algorithms/buffer/buffer_multi_linestring.cpp
  test/algorithms/buffer/buffer_multi_point.cpp
  test/algorithms/buffer/buffer_multi_polygon.cpp
  test/algorithms/buffer/buffer_point.cpp
  test/algorithms/buffer/buffer_point_geo.cpp
  test/algorithms/buffer/buffer_polygon.cpp
  test/algorithms/buffer/buffer_ring.cpp
  test/algorithms/buffer/buffer_with_strategies.cpp
  test/algorithms/buffer/test_buffer.hpp
  test/algorithms/buffer/test_buffer_geo.hpp
  test/algorithms/buffer/test_buffer_svg.hpp
  test/algorithms/buffer/test_buffer_svg_per_turn.hpp
Labels: enhancement

#526 Line interpolate point algorithm
  doc/doxy/doxygen_input/groups/groups.hpp
  doc/imports.qbk
  doc/make_qbk.py
  doc/quickref.xml
  doc/reference.qbk
  doc/reference/algorithms/line_interpolate.qbk
  doc/release_notes.qbk
  doc/src/docutils/tools/support_status/support_status.cpp
  doc/src/examples/algorithms/Jamfile.v2
  doc/src/examples/algorithms/line_interpolate.cpp
  doc/src/examples/algorithms/line_interpolate_strategy.cpp
  include/boost/geometry/algorithms/densify.hpp
  include/boost/geometry/algorithms/line_interpolate.hpp
  include/boost/geometry/formulas/interpolate_point_spherical.hpp
  include/boost/geometry/geometry.hpp
  include/boost/geometry/strategies/cartesian/line_interpolate.hpp
  include/boost/geometry/strategies/geographic/line_interpolate.hpp
  include/boost/geometry/strategies/line_interpolate.hpp
  include/boost/geometry/strategies/spherical/densify.hpp
  include/boost/geometry/strategies/spherical/line_interpolate.hpp
  include/boost/geometry/strategies/strategies.hpp
  test/algorithms/Jamfile.v2
  test/algorithms/line_interpolate.cpp
Labels: documentation, enhancement
