Repository boostorg/geometry, pull requests merged in 2019-11, with the labels that each got.

#502 Example: usage of distance formula
  example/ml03_distance_formula.cpp
Labels: enhancement

#634 [tests] Decrease accuracy in distance_cross_track geographic strategy…
  test/strategies/distance_cross_track.cpp
Labels: tests

#636 [strategies] Do not include karney strategy and parameters by default.
  include/boost/geometry/strategies/geographic/parameters.hpp
  include/boost/geometry/strategies/strategies.hpp
Labels: bug

#479 Fix for empty spherical union
  include/boost/geometry/algorithms/detail/expand_by_epsilon.hpp
  include/boost/geometry/algorithms/detail/sections/sectionalize.hpp
  include/boost/geometry/policies/robustness/segment_ratio.hpp
  include/boost/geometry/strategies/cartesian/envelope.hpp
  include/boost/geometry/strategies/cartesian/envelope_box.hpp
  include/boost/geometry/strategies/geographic/envelope.hpp
  include/boost/geometry/strategies/geographic/intersection.hpp
  include/boost/geometry/strategies/spherical/envelope.hpp
  include/boost/geometry/strategies/spherical/envelope_box.hpp
  include/boost/geometry/strategies/spherical/intersection.hpp
  include/boost/geometry/util/math.hpp
  test/algorithms/set_operations/union/Jamfile.v2
  test/algorithms/set_operations/union/union_aa_sph.cpp
Labels: bug

#641 Fix deprecated header for floating_point_comparison
  extensions/test/gis/io/wkb/read_wkb.cpp
  extensions/test/gis/io/wkb/write_wkb.cpp
  extensions/test/index/rtree.cpp
  test/geometry_test_common.hpp
  test/io/wkt/wkt_multi.cpp
Labels: tests, warning

#644 Move math::difference_angle() because it uses C++11 std::reminder.
  include/boost/geometry/formulas/karney_inverse.hpp
  include/boost/geometry/util/math.hpp
  include/boost/geometry/util/normalize_spheroidal_coordinates.hpp
Labels: bug

#645 fixing `Wunused-parameter` warnings
  include/boost/geometry/strategies/cartesian/buffer_end_round.hpp
  include/boost/geometry/strategies/transform/matrix_transformers.hpp
Labels: warning

#647 Fix odr-used constants and improve const-correctness in karney_inverse.
  include/boost/geometry/formulas/karney_inverse.hpp
Labels: bug

#648 [TEST] add testcases for reported issues
  test/algorithms/overlay/multi_overlay_cases.hpp
  test/algorithms/set_operations/difference/difference_multi.cpp
  test/algorithms/set_operations/intersection/intersection_multi.cpp
  test/algorithms/set_operations/union/union_multi.cpp
Labels: tests
