Repository boostorg/geometry, pull requests merged in 2019-06, with the labels that each got.

#594 Test/changes in defines
  include/boost/geometry/core/config.hpp
  test/algorithms/buffer/buffer_linestring.cpp
  test/algorithms/buffer/buffer_linestring_aimes.cpp
  test/algorithms/buffer/buffer_multi_point.cpp
  test/algorithms/buffer/buffer_multi_polygon.cpp
  test/algorithms/buffer/buffer_polygon.cpp
  test/algorithms/buffer/test_buffer.hpp
  test/algorithms/buffer/test_buffer_svg.hpp
  test/algorithms/envelope_expand/envelope_on_spheroid.cpp
  test/algorithms/envelope_expand/test_envelope_expand_on_spheroid.hpp
  test/algorithms/is_valid.cpp
  test/algorithms/overlay/get_turns_linear_linear.cpp
  test/algorithms/overlay/overlay_cases.hpp
  test/algorithms/overlay/traverse.cpp
  test/algorithms/overlay/traverse_multi.cpp
  test/algorithms/set_operations/difference/difference.cpp
  test/algorithms/set_operations/difference/difference_linear_linear.cpp
  test/algorithms/set_operations/difference/difference_multi.cpp
  test/algorithms/set_operations/difference/difference_multi_spike.cpp
  test/algorithms/set_operations/difference/test_difference.hpp
  test/algorithms/set_operations/intersection/intersection.cpp
  test/algorithms/set_operations/intersection/intersection_multi.cpp
  test/algorithms/set_operations/intersection/test_intersection.hpp
  test/algorithms/set_operations/sym_difference/sym_difference_linear_linear.cpp
  test/algorithms/set_operations/union/test_union.hpp
  test/algorithms/set_operations/union/union.cpp
  test/algorithms/set_operations/union/union_multi.cpp
  test/robustness/overlay/areal_areal/general_intersection_precision.cpp
Labels: tests

#572 Fix azimuth validity in geographic_point_circle buffer strategy.
  include/boost/geometry/formulas/differential_quantities.hpp
  include/boost/geometry/formulas/thomas_direct.hpp
  include/boost/geometry/strategies/geographic/buffer_point_circle.hpp
Labels: bug

#606 Fix of issue #596 - [buffer] fix line/line intersection point calculation for some cases,
  include/boost/geometry/algorithms/detail/buffer/line_line_intersection.hpp
  test/algorithms/buffer/buffer_linestring.cpp
Labels: bug

#607 Fix/various warnings
  include/boost/geometry/algorithms/detail/is_valid/has_spikes.hpp
  include/boost/geometry/algorithms/detail/is_valid/multipolygon.hpp
  include/boost/geometry/algorithms/detail/is_valid/polygon.hpp
  include/boost/geometry/algorithms/detail/overlay/get_distance_measure.hpp
  include/boost/geometry/algorithms/detail/overlay/handle_colocations.hpp
  include/boost/geometry/algorithms/detail/overlay/sort_by_side.hpp
  include/boost/geometry/algorithms/detail/overlay/traversal.hpp
  include/boost/geometry/io/wkt/write.hpp
Labels: bug, warning
