Repository boostorg/geometry, pull requests merged in 2020-06, with the labels that each got.

#722 Make index::detail::rtree::visitors::insert base class public
  include/boost/geometry/index/detail/rtree/visitors/insert.hpp
Labels: bug

#720 Add custom pack allocator to r-tree constructor
  doc/geometry.qbk
  include/boost/geometry/index/detail/rtree/pack_create.hpp
  include/boost/geometry/index/rtree.hpp
Labels: enhancement

#730 Fix MSVC warning C4127: conditional expression is constant
  include/boost/geometry/algorithms/detail/overlay/follow.hpp
  include/boost/geometry/algorithms/detail/overlay/follow_linear_linear.hpp
Labels: warning
