Repository boostorg/geometry, pull requests merged in 2020-08, with the labels that each got.

#740 Fix dangling references for referring_segment and proxy references returned by iterators.
  include/boost/geometry/algorithms/detail/buffer/piece_border.hpp
  include/boost/geometry/algorithms/detail/disjoint/linear_segment_or_box.hpp
  include/boost/geometry/algorithms/detail/overlay/get_turn_info_helpers.hpp
  include/boost/geometry/algorithms/detail/overlay/get_turns.hpp
  include/boost/geometry/algorithms/for_each.hpp
  include/boost/geometry/strategies/geographic/intersection.hpp
  include/boost/geometry/strategies/intersection_strategies.hpp
Labels: bug

#741 Fix/handle as touch
  include/boost/geometry/algorithms/detail/overlay/get_turn_info.hpp
  test/algorithms/buffer/buffer_linestring_aimes.cpp
  test/algorithms/buffer/buffer_multi_linestring.cpp
  test/algorithms/set_operations/union/union.cpp
Labels: bug

#744 [get_turn_info] Remove the recently added is_ii
  include/boost/geometry/algorithms/detail/overlay/get_turn_info.hpp
  test/algorithms/set_operations/difference/difference.cpp
Labels: bug

#745 Support constexpr in points, segment, box, get, dot and cross products.
  .github/workflows/minimal-clang.yml
  .github/workflows/minimal-gcc.yml
  include/boost/geometry/arithmetic/cross_product.hpp
  include/boost/geometry/arithmetic/dot_product.hpp
  include/boost/geometry/core/access.hpp
  include/boost/geometry/core/coordinate_dimension.hpp
  include/boost/geometry/geometries/box.hpp
  include/boost/geometry/geometries/point.hpp
  include/boost/geometry/geometries/point_xy.hpp
  include/boost/geometry/geometries/point_xyz.hpp
  include/boost/geometry/geometries/segment.hpp
Labels: enhancement

#733 Add example showing how std::array<T, N> can model the Point concept
  doc/concept/point.qbk
Labels: documentation
