Repository boostorg/geometry, pull requests merged in 2020-11, with the labels that each got.

#775 Fix unused parameter warnings
  include/boost/geometry/algorithms/detail/envelope/segment.hpp
  include/boost/geometry/strategies/area/cartesian.hpp
Labels: warning

#763 fixed risk of undefined behavior when parsing a byte_order byte
  include/boost/geometry/extensions/gis/io/wkb/detail/parser.hpp
Labels: bug

#772 Add constexpr and boost::variant workarounds for vs2015.
  include/boost/geometry/algorithms/area_result.hpp
  include/boost/geometry/arithmetic/cross_product.hpp
  include/boost/geometry/arithmetic/dot_product.hpp
  include/boost/geometry/geometries/point.hpp
  include/boost/geometry/strategies/comparable_distance_result.hpp
  include/boost/geometry/strategies/default_length_result.hpp
  include/boost/geometry/strategies/distance_result.hpp
Labels: workaround

#773 Fix turns where segments arrive at an intersection point, or leave
  include/boost/geometry/algorithms/detail/overlay/debug_turn_info.hpp
  include/boost/geometry/algorithms/detail/overlay/get_turn_info.hpp
  test/algorithms/buffer/buffer_linestring.cpp
  test/algorithms/buffer/buffer_multi_polygon.cpp
  test/algorithms/set_operations/difference/difference.cpp
  test/algorithms/set_operations/intersection/intersection.cpp
  test/algorithms/set_operations/union/union.cpp
  test/algorithms/set_operations/union/union_multi.cpp
Labels: bug

#778 Fixes/workarounds for clang 3.5-3.9
  include/boost/geometry/algorithms/area_result.hpp
  include/boost/geometry/geometries/point.hpp
  include/boost/geometry/geometries/variant.hpp
  include/boost/geometry/srs/projections/dpar.hpp
  include/boost/geometry/strategies/comparable_distance_result.hpp
  include/boost/geometry/strategies/default_length_result.hpp
  include/boost/geometry/strategies/distance_result.hpp
Labels: bug, workaround

#747 Add optional traits::make and use it in cross_product() and make().
  include/boost/geometry/algorithms/make.hpp
  include/boost/geometry/arithmetic/cross_product.hpp
  include/boost/geometry/core/make.hpp
  include/boost/geometry/geometries/box.hpp
  include/boost/geometry/geometries/concepts/check.hpp
  include/boost/geometry/geometries/geometries.hpp
  include/boost/geometry/geometries/point.hpp
  include/boost/geometry/geometries/point_xy.hpp
  include/boost/geometry/geometries/point_xyz.hpp
  include/boost/geometry/geometries/segment.hpp
  test/algorithms/make.cpp
  test/arithmetic/cross_product.cpp
  test/arithmetic/dot_product.cpp
  test/geometries/box.cpp
  test/geometries/point.cpp
  test/geometries/point_xy.cpp
  test/geometries/point_xyz.cpp
  test/geometries/segment.cpp
Labels: bug, enhancement
