Repository boostorg/geometry, pull requests merged in 2020-03, with the labels that each got.

#671 Add point_xyz as pre-defined geometry model
  doc/imports.qbk
  doc/make_qbk.py
  doc/quickref.xml
  doc/reference.qbk
  doc/reference/geometries/point_xyz.qbk
  doc/src/examples/geometries/Jamfile.v2
  doc/src/examples/geometries/point_xyz.cpp
  include/boost/geometry/geometries/point_xyz.hpp
  test/geometries/Jamfile.v2
  test/geometries/point_xyz.cpp
Labels: enhancement

#677 Deleted extra note in point_xy documentation
  doc/reference/geometries/point_xy.qbk
Labels: documentation

#680 Add GitHub Actions to build test//minimal with Clang, GCC, MSVC
  .github/workflows/minimal-clang.yml
  .github/workflows/minimal-gcc.yml
  .github/workflows/minimal-msvc.yml
Labels: enhancement

#660 Add dot_product example to documentation
  doc/imports.qbk
  doc/src/examples/arithmetic/dot_product.cpp
  include/boost/geometry/arithmetic/dot_product.hpp
Labels: documentation

#665 Add cross_product example to documentation
  doc/imports.qbk
  doc/make_qbk.py
  doc/src/examples/arithmetic/cross_product.cpp
  include/boost/geometry/arithmetic/cross_product.hpp
Labels: documentation

#687 Fix dangling reference in distance
  include/boost/geometry/algorithms/detail/distance/multipoint_to_geometry.hpp
  include/boost/geometry/srs/spheroid.hpp
Labels: bug

#685 Add missing headers to precise_math.hpp
  extensions/test/headers/Jamfile
  include/boost/geometry/extensions/triangulation/strategies/cartesian/detail/precise_math.hpp
Labels: extensions

#650 Missing input combinations in intersection() and introduction of tupled-output.
  include/boost/geometry/algorithms/detail/intersection/areal_areal.hpp
  include/boost/geometry/algorithms/detail/intersection/implementation.hpp
  include/boost/geometry/algorithms/detail/intersection/interface.hpp
  include/boost/geometry/algorithms/detail/intersection/multi.hpp
  include/boost/geometry/algorithms/detail/overlay/follow.hpp
  include/boost/geometry/algorithms/detail/overlay/follow_linear_linear.hpp
  include/boost/geometry/algorithms/detail/overlay/intersection_insert.hpp
  include/boost/geometry/algorithms/detail/overlay/pointlike_areal.hpp
  include/boost/geometry/algorithms/detail/overlay/pointlike_linear.hpp
  include/boost/geometry/algorithms/detail/overlay/pointlike_pointlike.hpp
  include/boost/geometry/algorithms/detail/relate/de9im.hpp
  include/boost/geometry/algorithms/detail/tupled_output.hpp
  include/boost/geometry/core/config.hpp
  include/boost/geometry/index/detail/tuples.hpp
  include/boost/geometry/index/predicates.hpp
  include/boost/geometry/srs/projections/impl/pj_datum_set.hpp
  include/boost/geometry/srs/projections/impl/pj_ell_set.hpp
  include/boost/geometry/srs/projections/impl/pj_init.hpp
  include/boost/geometry/srs/projections/impl/pj_param.hpp
  include/boost/geometry/srs/projections/proj/aeqd.hpp
  include/boost/geometry/srs/projections/proj/ob_tran.hpp
  include/boost/geometry/srs/projections/spar.hpp
  include/boost/geometry/util/tuples.hpp
  test/algorithms/detail/Jamfile
  test/algorithms/detail/tupled_output.cpp
  test/algorithms/set_operations/difference/Jamfile
  test/algorithms/set_operations/difference/difference_pl_a.cpp
  test/algorithms/set_operations/intersection/Jamfile
  test/algorithms/set_operations/intersection/intersection_pl_a.cpp
  test/algorithms/set_operations/intersection/intersection_tupled.cpp
  test/algorithms/set_operations/test_set_ops_pointlike.hpp
  test/util/Jamfile
  test/util/tuples.cpp
Labels: enhancement

#689 Deprecate C++03 in Boost 1.73 as preparation for C+14 switch
  README.md
  doc/compiling.qbk
  include/boost/geometry/geometry.hpp
Labels: documentation, warning
