Repository boostorg/geometry, pull requests merged in 2020-12, with the labels that each got.

#783 Add "cxxstd" json field to meta/libraries.json
  meta/libraries.json
Labels: documentation

#756 Non cartesian and robust convex hulls
  extensions/test/triangulation/side_robust.cpp
  include/boost/geometry/algorithms/convex_hull.hpp
  include/boost/geometry/algorithms/detail/convex_hull/graham_andrew.hpp
  include/boost/geometry/algorithms/detail/convex_hull/interface.hpp
  include/boost/geometry/strategies/cartesian.hpp
  include/boost/geometry/strategies/convex_hull/cartesian.hpp
  include/boost/geometry/strategies/convex_hull/geographic.hpp
  include/boost/geometry/strategies/convex_hull/services.hpp
  include/boost/geometry/strategies/convex_hull/spherical.hpp
  include/boost/geometry/strategies/geographic.hpp
  include/boost/geometry/strategies/geographic/side.hpp
  include/boost/geometry/strategies/spherical.hpp
  include/boost/geometry/strategies/spherical/side_by_cross_track.hpp
  include/boost/geometry/strategies/strategies.hpp
  include/boost/geometry/strategy/cartesian/in_circle_robust.hpp
  include/boost/geometry/strategy/cartesian/precise_area.hpp
  include/boost/geometry/strategy/cartesian/side_non_robust.hpp
  include/boost/geometry/strategy/cartesian/side_robust.hpp
  test/algorithms/Jamfile
  test/algorithms/convex_hull/Jamfile
  test/algorithms/convex_hull/convex_hull.cpp
  test/algorithms/convex_hull/convex_hull_multi.cpp
  test/algorithms/convex_hull/convex_hull_robust.cpp
  test/algorithms/convex_hull/convex_hull_sph_geo.cpp
  test/algorithms/convex_hull/test_convex_hull.hpp
  test/algorithms/test_convex_hull.hpp
Labels: enhancement

#786 Catch up with dms_parser change from function call operator to apply
  include/boost/geometry/extensions/algorithms/parse.hpp
Labels: bug, extensions

#785 [strategies] [test] Fix spherical cross track and convex hull tests
  include/boost/geometry/strategies/spherical/side_by_cross_track.hpp
  test/algorithms/Jamfile
Labels: tests

#780 Fix/sort by side point at turn
  include/boost/geometry/algorithms/detail/overlay/copy_segment_point.hpp
  include/boost/geometry/algorithms/detail/overlay/get_ring.hpp
  include/boost/geometry/algorithms/detail/overlay/handle_colocations.hpp
  include/boost/geometry/algorithms/detail/overlay/segment_identifier.hpp
  include/boost/geometry/algorithms/detail/overlay/sort_by_side.hpp
  include/boost/geometry/algorithms/detail/overlay/traversal.hpp
  test/algorithms/buffer/buffer_multi_polygon.cpp
  test/algorithms/buffer/test_buffer_svg.hpp
  test/algorithms/overlay/Jamfile
  test/algorithms/overlay/copy_segment_point.cpp
  test/algorithms/overlay/sort_by_side.cpp
  test/algorithms/overlay/sort_by_side_basic.cpp
  test/algorithms/set_operations/difference/difference.cpp
  test/algorithms/set_operations/difference/difference_multi.cpp
  test/algorithms/set_operations/intersection/intersection_multi.cpp
  test/algorithms/set_operations/union/union_multi.cpp
  test/count_set.hpp
Labels: bug
