Repository boostorg/geometry, pull requests merged in 2020-10, with the labels that each got.

#751 resolve c2146 on vs15 with area_result declaration
  include/boost/geometry/algorithms/area_result.hpp
Labels: compiler bug

#758 Conform the countset, replace many #ifdefs with expectation limits
  test/algorithms/buffer/buffer_countries.cpp
  test/algorithms/buffer/buffer_linestring.cpp
  test/algorithms/buffer/buffer_linestring_aimes.cpp
  test/algorithms/buffer/buffer_multi_linestring.cpp
  test/algorithms/buffer/buffer_multi_polygon.cpp
  test/algorithms/buffer/buffer_polygon.cpp
  test/algorithms/buffer/test_buffer.hpp
  test/algorithms/set_operations/difference/difference.cpp
  test/algorithms/set_operations/difference/difference_multi.cpp
  test/algorithms/set_operations/difference/test_difference.hpp
  test/algorithms/set_operations/intersection/intersection.cpp
  test/algorithms/set_operations/intersection/intersection_multi.cpp
  test/algorithms/set_operations/intersection/test_intersection.hpp
  test/algorithms/set_operations/union/test_union.hpp
  test/algorithms/set_operations/union/union.cpp
  test/algorithms/set_operations/union/union_multi.cpp
  test/count_set.hpp
  test/expectation_limits.hpp
  test/geometry_test_common.hpp
Labels: tests

#767 Modernize tuple-related code.
  include/boost/geometry/algorithms/detail/overlay/get_turn_info_for_endpoint.hpp
  include/boost/geometry/algorithms/detail/overlay/get_turn_info_helpers.hpp
  include/boost/geometry/algorithms/detail/relate/de9im.hpp
  include/boost/geometry/algorithms/detail/relate/interface.hpp
  include/boost/geometry/algorithms/detail/relate/result.hpp
  include/boost/geometry/algorithms/detail/tupled_output.hpp
  include/boost/geometry/index/detail/predicates.hpp
  include/boost/geometry/index/detail/rtree/utilities/statistics.hpp
  include/boost/geometry/index/predicates.hpp
  include/boost/geometry/index/rtree.hpp
  include/boost/geometry/policies/relate/intersection_policy.hpp
  include/boost/geometry/policies/relate/tupled.hpp
  include/boost/geometry/srs/projection.hpp
  include/boost/geometry/srs/projections/impl/pj_datum_set.hpp
  include/boost/geometry/srs/projections/impl/pj_ell_set.hpp
  include/boost/geometry/srs/projections/impl/pj_init.hpp
  include/boost/geometry/srs/projections/impl/pj_param.hpp
  include/boost/geometry/srs/projections/proj/ob_tran.hpp
  include/boost/geometry/srs/projections/spar.hpp
  include/boost/geometry/strategies/intersection_strategies.hpp
  include/boost/geometry/util/tuples.hpp
  test/strategies/segment_intersection.cpp
  test/strategies/segment_intersection_collinear.cpp
  test/strategies/segment_intersection_sph.hpp
  test/util/tuples.cpp
Labels: enhancement
