Repository boostorg/geometry, pull requests merged in 2020-05, with the labels that each got.

#708 [buffer] remove rescaling from the turn-in-original check
  include/boost/geometry/algorithms/detail/buffer/buffer_policies.hpp
  include/boost/geometry/algorithms/detail/buffer/buffered_piece_collection.hpp
  include/boost/geometry/algorithms/detail/buffer/turn_in_original_visitor.hpp
Labels: enhancement

#701 Performance improvements for side_robust
  include/boost/geometry/extensions/triangulation/strategies/cartesian/detail/precise_math.hpp
  include/boost/geometry/extensions/triangulation/strategies/cartesian/side_robust.hpp
Labels: enhancement, extensions

#710 [index] Use memcpy and memmove only if T is_trivially_copyable.
  include/boost/geometry/index/detail/varray_detail.hpp
Labels: bug

#695 Support tupled-output in difference, sym_difference and union_.
  include/boost/geometry/algorithms/detail/intersection/areal_areal.hpp
  include/boost/geometry/algorithms/detail/intersection/multi.hpp
  include/boost/geometry/algorithms/detail/overlay/intersection_insert.hpp
  include/boost/geometry/algorithms/detail/tupled_output.hpp
  include/boost/geometry/algorithms/difference.hpp
  include/boost/geometry/algorithms/sym_difference.hpp
  include/boost/geometry/algorithms/union.hpp
  test/algorithms/set_operations/difference/Jamfile
  test/algorithms/set_operations/difference/difference_tupled.cpp
  test/algorithms/set_operations/sym_difference/Jamfile
  test/algorithms/set_operations/sym_difference/sym_difference_tupled.cpp
  test/algorithms/set_operations/union/Jamfile
  test/algorithms/set_operations/union/union_tupled.cpp
Labels: enhancement

#712 [overlay] Fix possible instabilities in sort_by_side
  include/boost/geometry/algorithms/detail/overlay/handle_colocations.hpp
  include/boost/geometry/algorithms/detail/overlay/sort_by_side.hpp
Labels: bug
