Repository boostorg/geometry, pull requests merged in 2021-02, with the labels that each got.

#798 Fix MSVC warning C4267: '=': conversion from 'size_t' to 'int'
  include/boost/geometry/extensions/algorithms/detail/overlay/dissolver.hpp
Labels: extensions, warning

#779 [test] Include only necessary headers of Boost.Range.
  test/algorithms/distance/distance_brute_force.hpp
  test/algorithms/distance/distance_geo_linear_box.cpp
  test/algorithms/distance/distance_se_geo_ar_ar.cpp
  test/algorithms/distance/distance_se_geo_l_ar.cpp
  test/algorithms/distance/distance_se_geo_l_l.cpp
  test/algorithms/distance/distance_se_geo_pl_ar.cpp
  test/algorithms/distance/distance_se_pl_pl.cpp
  test/algorithms/set_operations/check_turn_less.hpp
  test/algorithms/set_operations/difference/test_difference.hpp
  test/algorithms/set_operations/difference/test_difference_linear_linear.hpp
  test/algorithms/set_operations/intersection/intersection_areal_areal_linear.cpp
  test/algorithms/set_operations/intersection/test_intersection.hpp
  test/algorithms/set_operations/intersection/test_intersection_linear_linear.hpp
  test/algorithms/set_operations/sym_difference/test_sym_difference_linear_linear.hpp
  test/algorithms/set_operations/test_get_turns_ll_invariance.hpp
  test/algorithms/set_operations/test_set_ops_linear_linear.hpp
  test/algorithms/set_operations/test_set_ops_pointlike.hpp
  test/algorithms/set_operations/union/test_union.hpp
  test/algorithms/set_operations/union/test_union_linear_linear.hpp
  test/algorithms/test_is_valid.hpp
  test/geometries/initialization.cpp
  test/test_geometries/all_custom_linestring.hpp
  test/test_geometries/all_custom_polygon.hpp
  test/test_geometries/all_custom_ring.hpp
  test/test_geometries/wrapped_boost_array.hpp
Labels: enhancement, tests

#802 [test] Add tests for /extensions/algorithms/parse.hpp
  extensions/test/algorithms/Jamfile
  extensions/test/algorithms/parse.cpp
Labels: tests

#806 Add unit test for parse.hpp
  extensions/test/algorithms/parse.cpp
Labels: tests

#797 Add new algorithm azimuth.
  doc/doxy/doxygen_input/groups/groups.hpp
  doc/imports.qbk
  doc/make_qbk.py
  doc/quickref.xml
  doc/reference.qbk
  doc/reference/algorithms/azimuth.qbk
  doc/src/examples/algorithms/azimuth.cpp
  doc/src/examples/algorithms/azimuth_strategy.cpp
  include/boost/geometry/algorithms/azimuth.hpp
  include/boost/geometry/algorithms/detail/azimuth.hpp
  include/boost/geometry/algorithms/detail/course.hpp
  include/boost/geometry/geometry.hpp
  include/boost/geometry/strategies/azimuth.hpp
  include/boost/geometry/strategies/azimuth/cartesian.hpp
  include/boost/geometry/strategies/azimuth/geographic.hpp
  include/boost/geometry/strategies/azimuth/services.hpp
  include/boost/geometry/strategies/azimuth/spherical.hpp
  include/boost/geometry/strategies/cartesian.hpp
  include/boost/geometry/strategies/cartesian/azimuth.hpp
  include/boost/geometry/strategies/geographic.hpp
  include/boost/geometry/strategies/geographic/azimuth.hpp
  include/boost/geometry/strategies/spherical.hpp
  include/boost/geometry/strategies/spherical/azimuth.hpp
  test/algorithms/Jamfile
  test/algorithms/azimuth.cpp
Labels: enhancement

#808 Fix build in index serialization
  include/boost/geometry/index/detail/serialization.hpp
Labels: bug

#774 [svg] Add scale function and examples of it
  doc/html/img/io/svg_mapper_scale.png
  doc/imports.qbk
  doc/reference/io/svg.qbk
  doc/src/examples/io/Jamfile
  doc/src/examples/io/svg.cpp
  doc/src/examples/io/svg_mapper_scale.cpp
  include/boost/geometry/io/svg/svg_mapper.hpp
  test/io/svg/svg.cpp
  test/to_svg.hpp
Labels: enhancement

#816 Remove detailed list of compilers and versions form the docs
  doc/compiling.qbk
Labels: documentation

#815 [buffer] fix case for issue 803
  include/boost/geometry/algorithms/detail/buffer/buffer_inserter.hpp
  include/boost/geometry/algorithms/detail/buffer/line_line_intersection.hpp
  include/boost/geometry/arithmetic/infinite_line_functions.hpp
  include/boost/geometry/geometries/infinite_line.hpp
  include/boost/geometry/strategies/cartesian/buffer_side_straight.hpp
  test/algorithms/buffer/buffer_linestring.cpp
  test/algorithms/buffer/buffer_polygon.cpp
Labels: bug
