Repository boostorg/geometry, pull requests merged in 2021-05, with the labels that each got.

#854 Update line_interpolate tests
  test/algorithms/line_interpolate.cpp
Labels: tests

#853 Add missing case for geo segment-box disjoint
  include/boost/geometry/algorithms/detail/disjoint/segment_box.hpp
  test/algorithms/disjoint/disjoint_seg_box.cpp
Labels: bug

#841 Fixed ring concept non-existent header file
  doc/concept/ring.qbk
Labels: documentation
