Repository boostorg/geometry, pull requests merged in 2021-03, with the labels that each got.

#801 Improve accuracy in geographic area computations
  include/boost/geometry/formulas/area_formulas.hpp
  include/boost/geometry/formulas/karney_inverse.hpp
  include/boost/geometry/formulas/spherical.hpp
  include/boost/geometry/strategies/geographic/parameters.hpp
  include/boost/geometry/strategies/strategies.hpp
  include/boost/geometry/strategy/geographic/area.hpp
  test/algorithms/area/area.cpp
  test/algorithms/area/area_geo.cpp
  test/algorithms/area/area_multi.cpp
  test/algorithms/area/area_sph_geo.cpp
  test/algorithms/convex_hull/convex_hull_sph_geo.cpp
  test/algorithms/distance/distance_geo_linear_box.cpp
  test/algorithms/distance/distance_geo_pl_l.cpp
  test/algorithms/distance/distance_se_geo_ar_ar.cpp
  test/algorithms/distance/distance_se_geo_l_ar.cpp
  test/algorithms/distance/distance_se_geo_l_l.cpp
  test/algorithms/distance/distance_se_geo_pl_ar.cpp
  test/algorithms/distance/distance_se_geo_pl_pl.cpp
  test/algorithms/distance/test_distance_geo_common.hpp
  test/formulas/inverse_karney.cpp
Labels: bug, enhancement

#823 Fix vec_normalize namespace
  include/boost/geometry/formulas/geographic.hpp
Labels: tests

#820 [svg] changes newly added scale function in a constructor parameter
  doc/html/img/io/svg_mapper_custom.png
  doc/html/img/io/svg_mapper_scale.png
  doc/imports.qbk
  doc/reference/io/svg.qbk
  doc/src/examples/io/Jamfile
  doc/src/examples/io/svg_mapper_custom.cpp
  include/boost/geometry/io/svg/svg_mapper.hpp
Labels: enhancement

#822 Fix Documentation error in Area strategy
  doc/doxy/Doxyfile
Labels: documentation

#824 [test][area] Tweak error thresholds for small areas.
  test/algorithms/area/area_sph_geo.cpp
Labels: tests

#827 Add for_each_dimension and more.
  include/boost/geometry/algorithms/assign.hpp
  include/boost/geometry/algorithms/centroid.hpp
  include/boost/geometry/algorithms/detail/assign_indexed_point.hpp
  include/boost/geometry/algorithms/detail/assign_values.hpp
  include/boost/geometry/algorithms/detail/extreme_points.hpp
  include/boost/geometry/arithmetic/arithmetic.hpp
  include/boost/geometry/extensions/algebra/algorithms/transform_geometrically.hpp
  include/boost/geometry/extensions/algebra/algorithms/translation.hpp
  include/boost/geometry/formulas/geographic.hpp
  include/boost/geometry/strategies/cartesian/centroid_weighted_length.hpp
  include/boost/geometry/strategies/cartesian/densify.hpp
  include/boost/geometry/strategies/cartesian/line_interpolate.hpp
  include/boost/geometry/strategies/spherical/intersection.hpp
  include/boost/geometry/util/algorithm.hpp
  test/util/Jamfile
  test/util/algorithm.cpp
Labels: enhancement

#812 Umbrella strategies for distance() and comparable_distance().
  include/boost/geometry/algorithms/detail/closest_feature/point_to_range.hpp
  include/boost/geometry/algorithms/detail/closest_feature/range_to_range.hpp
  include/boost/geometry/algorithms/detail/comparable_distance/interface.hpp
  include/boost/geometry/algorithms/detail/distance/backward_compatibility.hpp
  include/boost/geometry/algorithms/detail/distance/box_to_box.hpp
  include/boost/geometry/algorithms/detail/distance/default_strategies.hpp
  include/boost/geometry/algorithms/detail/distance/geometry_to_segment_or_box.hpp
  include/boost/geometry/algorithms/detail/distance/implementation.hpp
  include/boost/geometry/algorithms/detail/distance/interface.hpp
  include/boost/geometry/algorithms/detail/distance/linear_or_areal_to_areal.hpp
  include/boost/geometry/algorithms/detail/distance/linear_to_box.hpp
  include/boost/geometry/algorithms/detail/distance/linear_to_linear.hpp
  include/boost/geometry/algorithms/detail/distance/multipoint_to_geometry.hpp
  include/boost/geometry/algorithms/detail/distance/point_to_geometry.hpp
  include/boost/geometry/algorithms/detail/distance/range_to_geometry_rtree.hpp
  include/boost/geometry/algorithms/detail/distance/segment_to_box.hpp
  include/boost/geometry/algorithms/detail/distance/segment_to_segment.hpp
  include/boost/geometry/algorithms/detail/distance/strategy_utils.hpp
  include/boost/geometry/algorithms/dispatch/distance.hpp
  include/boost/geometry/algorithms/simplify.hpp
  include/boost/geometry/index/detail/distance_predicates.hpp
  include/boost/geometry/index/detail/rtree/rstar/insert.hpp
  include/boost/geometry/strategies/cartesian.hpp
  include/boost/geometry/strategies/cartesian/distance_segment_box.hpp
  include/boost/geometry/strategies/comparable_distance_result.hpp
  include/boost/geometry/strategies/detail.hpp
  include/boost/geometry/strategies/distance.hpp
  include/boost/geometry/strategies/distance/backward_compatibility.hpp
  include/boost/geometry/strategies/distance/cartesian.hpp
  include/boost/geometry/strategies/distance/comparable.hpp
  include/boost/geometry/strategies/distance/detail.hpp
  include/boost/geometry/strategies/distance/geographic.hpp
  include/boost/geometry/strategies/distance/services.hpp
  include/boost/geometry/strategies/distance/spherical.hpp
  include/boost/geometry/strategies/distance_result.hpp
  include/boost/geometry/strategies/envelope/spherical.hpp
  include/boost/geometry/strategies/expand/spherical.hpp
  include/boost/geometry/strategies/geographic.hpp
  include/boost/geometry/strategies/geographic/distance_cross_track.hpp
  include/boost/geometry/strategies/geographic/distance_cross_track_box_box.hpp
  include/boost/geometry/strategies/geographic/distance_cross_track_point_box.hpp
  include/boost/geometry/strategies/geographic/distance_segment_box.hpp
  include/boost/geometry/strategies/index/cartesian.hpp
  include/boost/geometry/strategies/index/geographic.hpp
  include/boost/geometry/strategies/index/spherical.hpp
  include/boost/geometry/strategies/relate/spherical.hpp
  include/boost/geometry/strategies/spherical.hpp
  include/boost/geometry/strategies/spherical/distance_segment_box.hpp
  include/boost/geometry/util/type_traits.hpp
  test/algorithms/distance/test_distance_common.hpp
Labels: enhancement
