Repository boostorg/geometry, pull requests merged in 2021-07, with the labels that each got.

#878 Fix initializer lists
  include/boost/geometry/strategy/cartesian/side_robust.hpp
  test/algorithms/overlay/get_clusters.cpp
Labels: bug

#882 Remove sum_error function
  include/boost/geometry/formulas/karney_inverse.hpp
  include/boost/geometry/util/math.hpp
  test/formulas/inverse.cpp
  test/formulas/inverse_cases_small_angles.hpp
  test/formulas/inverse_karney.cpp
  test/formulas/test_formula.hpp
Labels: warning

#883 Fix various warnings, e.g. remove unused variables, etc.
  include/boost/geometry/algorithms/detail/sections/section_functions.hpp
  include/boost/geometry/algorithms/difference.hpp
  include/boost/geometry/iterators/concatenate_iterator.hpp
  include/boost/geometry/iterators/flatten_iterator.hpp
  include/boost/geometry/srs/projections/factory.hpp
  include/boost/geometry/srs/projections/proj/igh.hpp
  test/concepts/point_spherical_with_wrong_units.cpp
  test/core/coordinate_dimension.cpp
  test/cs_undefined/test_relops.hpp
  test/geometries/initialization.cpp
  test/geometries/polygon.cpp
  test/util/algorithm.cpp
Labels: warning

#886 Fix traversing of the rtree during incremental knn query.
  include/boost/geometry/index/detail/predicates.hpp
  include/boost/geometry/index/detail/rtree/visitors/distance_query.hpp
  include/boost/geometry/index/detail/rtree/visitors/spatial_query.hpp
  include/boost/geometry/index/predicates.hpp
  include/boost/geometry/index/rtree.hpp
Labels: bug

#891 [test] remove the non used KRAMER define and some other changes in testing is_valid
  include/boost/geometry/core/config.hpp
  test/algorithms/set_operations/difference/difference.cpp
  test/algorithms/set_operations/difference/difference_multi.cpp
  test/algorithms/set_operations/difference/test_difference.hpp
  test/algorithms/set_operations/intersection/intersection.cpp
  test/algorithms/set_operations/intersection/intersection_multi.cpp
  test/algorithms/set_operations/union/union_multi.cpp
  test/geometry_test_common.hpp
Labels: tests
