Repository boostorg/geometry, pull requests merged in 2021-08, with the labels that each got.

#895 Fix error checking for failure type in example
  doc/src/examples/algorithms/is_valid_failure.cpp
Labels: documentation

#898 Add missing headers to satisfy Boost header policy.
  include/boost/geometry/algorithms/azimuth.hpp
  include/boost/geometry/index/detail/algorithms/bounds.hpp
  include/boost/geometry/index/detail/algorithms/comparable_distance_centroid.hpp
  include/boost/geometry/index/detail/algorithms/comparable_distance_far.hpp
  include/boost/geometry/index/detail/algorithms/comparable_distance_near.hpp
  include/boost/geometry/index/detail/algorithms/content.hpp
  include/boost/geometry/index/detail/algorithms/intersection_content.hpp
  include/boost/geometry/index/detail/algorithms/is_valid.hpp
  include/boost/geometry/index/detail/algorithms/margin.hpp
  include/boost/geometry/index/detail/algorithms/path_intersection.hpp
  include/boost/geometry/index/detail/algorithms/segment_intersection.hpp
  include/boost/geometry/index/detail/distance_predicates.hpp
  include/boost/geometry/index/detail/predicates.hpp
  include/boost/geometry/index/detail/rtree/adaptors.hpp
  include/boost/geometry/index/detail/rtree/iterators.hpp
  include/boost/geometry/index/detail/rtree/kmeans/kmeans.hpp
  include/boost/geometry/index/detail/rtree/kmeans/split.hpp
  include/boost/geometry/index/detail/rtree/node/node_elements.hpp
  include/boost/geometry/index/detail/rtree/node/scoped_deallocator.hpp
  include/boost/geometry/index/detail/rtree/node/variant_dynamic.hpp
  include/boost/geometry/index/detail/rtree/node/variant_static.hpp
  include/boost/geometry/index/detail/rtree/node/weak_dynamic.hpp
  include/boost/geometry/index/detail/rtree/node/weak_static.hpp
  include/boost/geometry/index/detail/rtree/node/weak_visitor.hpp
  include/boost/geometry/index/detail/rtree/pack_create.hpp
  include/boost/geometry/index/detail/rtree/query_iterators.hpp
  include/boost/geometry/index/detail/rtree/rstar/choose_next_node.hpp
  include/boost/geometry/index/detail/rtree/rstar/insert.hpp
  include/boost/geometry/index/detail/rtree/utilities/gl_draw.hpp
  include/boost/geometry/index/detail/rtree/utilities/print.hpp
  include/boost/geometry/index/detail/rtree/visitors/distance_query.hpp
  include/boost/geometry/index/detail/rtree/visitors/insert.hpp
  include/boost/geometry/index/detail/rtree/visitors/iterator.hpp
  include/boost/geometry/index/detail/rtree/visitors/remove.hpp
  include/boost/geometry/index/detail/rtree/visitors/spatial_query.hpp
  include/boost/geometry/index/detail/serialization.hpp
  include/boost/geometry/index/detail/translator.hpp
  include/boost/geometry/index/parameters.hpp
  include/boost/geometry/strategies/distance/comparable.hpp
  include/boost/geometry/strategies/distance/services.hpp
  include/boost/geometry/strategies/geographic/buffer_point_circle.hpp
  include/boost/geometry/strategies/intersection_result.hpp
  include/boost/geometry/strategies/relate/geographic.hpp
  include/boost/geometry/strategies/simplify/spherical.hpp
Labels: coding guidelines

#899 Various small fixes and improvements.
  include/boost/geometry/algorithms/detail/select_geometry_type.hpp
  include/boost/geometry/util/sequence.hpp
  test/algorithms/line_interpolate.cpp
  test/geometries/boost_array_as_point.cpp
  test/strategies/envelope_segment.cpp
  test/util/algorithm.cpp
Labels: warning, workaround
