Repository boostorg/geometry, pull requests merged in 2021-09, with the labels that each got.

#904 Fix compilation errors in extensions and tests.
  extensions/test/algorithms/connect.cpp
  extensions/test/triangulation/in_circle_robust.cpp
  include/boost/geometry/extensions/algorithms/distance_info.hpp
  include/boost/geometry/extensions/gis/io/wkb/detail/endian.hpp
  include/boost/geometry/extensions/nsphere/geometries/concepts/check.hpp
  include/boost/geometry/extensions/nsphere/geometries/concepts/nsphere_concept.hpp
  include/boost/geometry/extensions/nsphere/nsphere.hpp
Labels: tests, extensions

#894 Optimize rtree nearest queries, refactor spatial and nearest queries.
  include/boost/geometry/index/detail/maxmin_heap.hpp
  include/boost/geometry/index/detail/minmax_heap.hpp
  include/boost/geometry/index/detail/predicates.hpp
  include/boost/geometry/index/detail/priority_dequeue.hpp
  include/boost/geometry/index/detail/rtree/query_iterators.hpp
  include/boost/geometry/index/detail/rtree/visitors/distance_query.hpp
  include/boost/geometry/index/detail/rtree/visitors/spatial_query.hpp
  include/boost/geometry/index/rtree.hpp
  index/test/Jamfile
  index/test/minmax_heap.cpp
Labels: enhancement

#877 Support DG and GC in convex_hull, correct, correct_closure, is_convex, is_empty and reverse.
  include/boost/geometry/algorithms/correct.hpp
  include/boost/geometry/algorithms/correct_closure.hpp
  include/boost/geometry/algorithms/detail/as_range.hpp
  include/boost/geometry/algorithms/detail/convex_hull/graham_andrew.hpp
  include/boost/geometry/algorithms/detail/convex_hull/interface.hpp
  include/boost/geometry/algorithms/detail/multi_modify.hpp
  include/boost/geometry/algorithms/detail/select_geometry_type.hpp
  include/boost/geometry/algorithms/is_convex.hpp
  include/boost/geometry/algorithms/is_empty.hpp
  include/boost/geometry/algorithms/reverse.hpp
  include/boost/geometry/extensions/algorithms/remove_holes_if.hpp
  include/boost/geometry/geometries/adapted/boost_variant.hpp
  include/boost/geometry/geometries/concepts/check.hpp
  include/boost/geometry/strategies/convex_hull/cartesian.hpp
  include/boost/geometry/strategies/convex_hull/geographic.hpp
  include/boost/geometry/strategies/convex_hull/spherical.hpp
  include/boost/geometry/strategies/is_convex/cartesian.hpp
  include/boost/geometry/strategies/is_convex/geographic.hpp
  include/boost/geometry/strategies/is_convex/spherical.hpp
  include/boost/geometry/util/sequence.hpp
  include/boost/geometry/util/type_traits.hpp
  test/algorithms/convex_hull/test_convex_hull.hpp
  test/algorithms/detail/Jamfile
  test/algorithms/detail/as_range.cpp
  test/algorithms/is_convex.cpp
  test/algorithms/test_correct.hpp
Labels: enhancement

#908 Fix robust convex hull tests
  test/algorithms/convex_hull/convex_hull_robust.cpp
Labels: tests

#906 Fix buffer for macos-11, clang-12.0.5, x86-64
  include/boost/geometry/algorithms/detail/buffer/turn_in_piece_visitor.hpp
  test/algorithms/buffer/buffer_multi_linestring.cpp
Labels: bug
