Repository boostorg/geometry, pull requests merged in 2021-06, with the labels that each got.

#850 Add DynamicGeometry and GeometryCollection.
  include/boost/geometry/algorithms/append.hpp
  include/boost/geometry/algorithms/area.hpp
  include/boost/geometry/algorithms/area_result.hpp
  include/boost/geometry/algorithms/clear.hpp
  include/boost/geometry/algorithms/detail/buffer/buffered_ring.hpp
  include/boost/geometry/algorithms/detail/comparable_distance/interface.hpp
  include/boost/geometry/algorithms/detail/disjoint/interface.hpp
  include/boost/geometry/algorithms/detail/distance/interface.hpp
  include/boost/geometry/algorithms/detail/select_geometry_type.hpp
  include/boost/geometry/algorithms/detail/visit.hpp
  include/boost/geometry/algorithms/length.hpp
  include/boost/geometry/algorithms/simplify.hpp
  include/boost/geometry/core/geometry_types.hpp
  include/boost/geometry/core/mutable_range.hpp
  include/boost/geometry/core/tags.hpp
  include/boost/geometry/core/visit.hpp
  include/boost/geometry/extensions/gis/io/shapefile/read.hpp
  include/boost/geometry/geometries/adapted/boost_any.hpp
  include/boost/geometry/geometries/adapted/boost_variant.hpp
  include/boost/geometry/geometries/adapted/boost_variant2.hpp
  include/boost/geometry/geometries/adapted/detail/any.hpp
  include/boost/geometry/geometries/adapted/std_any.hpp
  include/boost/geometry/geometries/adapted/std_variant.hpp
  include/boost/geometry/geometries/concepts/box_concept.hpp
  include/boost/geometry/geometries/concepts/check.hpp
  include/boost/geometry/geometries/concepts/concept_type.hpp
  include/boost/geometry/geometries/concepts/dynamic_geometry_concept.hpp
  include/boost/geometry/geometries/concepts/geometry_collection_concept.hpp
  include/boost/geometry/geometries/concepts/linestring_concept.hpp
  include/boost/geometry/geometries/concepts/multi_linestring_concept.hpp
  include/boost/geometry/geometries/concepts/multi_point_concept.hpp
  include/boost/geometry/geometries/concepts/multi_polygon_concept.hpp
  include/boost/geometry/geometries/concepts/point_concept.hpp
  include/boost/geometry/geometries/concepts/polygon_concept.hpp
  include/boost/geometry/geometries/concepts/ring_concept.hpp
  include/boost/geometry/geometries/concepts/segment_concept.hpp
  include/boost/geometry/geometries/geometries.hpp
  include/boost/geometry/geometries/geometry_collection.hpp
  include/boost/geometry/geometries/variant.hpp
  include/boost/geometry/geometry.hpp
  include/boost/geometry/io/wkt/read.hpp
  include/boost/geometry/io/wkt/write.hpp
  include/boost/geometry/strategies/comparable_distance_result.hpp
  include/boost/geometry/strategies/default_length_result.hpp
  include/boost/geometry/strategies/distance_result.hpp
  include/boost/geometry/util/range.hpp
  include/boost/geometry/util/sequence.hpp
  include/boost/geometry/util/type_traits.hpp
  include/boost/geometry/util/type_traits_std.hpp
  test/algorithms/area/area.cpp
  test/algorithms/clear_multi.cpp
  test/algorithms/detail/Jamfile
  test/algorithms/detail/visit.cpp
  test/algorithms/disjoint/test_disjoint.hpp
  test/algorithms/test_length.hpp
  test/core/Jamfile
  test/core/point_type.cpp
  test/core/visit.cpp
  test/io/wkt/wkt.cpp
  test/util/range.cpp
Labels: enhancement

#866 Fix rtree serialization load for 1-level tree with number of elements lesser than min.
  include/boost/geometry/index/detail/serialization.hpp
Labels: bug

#871 [test] add cases for issues #869 and #861
  test/algorithms/overlay/multi_overlay_cases.hpp
  test/algorithms/overlay/overlay_cases.hpp
  test/algorithms/set_operations/difference/difference_multi.cpp
  test/algorithms/set_operations/intersection/intersection.cpp
  test/algorithms/set_operations/intersection/intersection_multi.cpp
  test/algorithms/set_operations/union/union_multi.cpp
Labels: bug

#872 [traverse] modernize code and add documentation, make clusters const
  include/boost/geometry/algorithms/detail/overlay/overlay.hpp
  include/boost/geometry/algorithms/detail/overlay/traversal_switch_detector.hpp
Labels: enhancement

#832 Area strategies for non-cartesian boxes.
  include/boost/geometry/algorithms/area.hpp
  include/boost/geometry/strategies/area/cartesian.hpp
  include/boost/geometry/strategies/area/geographic.hpp
  include/boost/geometry/strategies/area/spherical.hpp
  include/boost/geometry/strategy/cartesian/area_box.hpp
  include/boost/geometry/strategy/geographic/area_box.hpp
  include/boost/geometry/strategy/spherical/area_box.hpp
  test/algorithms/area/Jamfile
  test/algorithms/area/area_box_sg.cpp
Labels: bug, enhancement
