Repository boostorg/geometry, pull requests merged in 2022-01, with the labels that each got.

#939 Closest points algorithm with new strategies for spherical and geographic geometries except boxes
  doc/doxy/Doxyfile
  doc/doxy/doxygen_input/groups/groups.hpp
  doc/html/img/algorithms/closest_points.png
  doc/html/index.html
  doc/imports.qbk
  doc/make_qbk.py
  doc/quickref.xml
  doc/readme.txt
  doc/reference.qbk
  doc/src/docutils/tools/support_status/support_status.cpp
  doc/src/examples/algorithms/Jamfile
  doc/src/examples/algorithms/closest_points.cpp
  doc/src/examples/algorithms/closest_points_strategy.cpp
  doc/src/examples/examples_utils/create_svg_closest_points.hpp
  include/boost/geometry/algorithms/detail/closest_points/implementation.hpp
  include/boost/geometry/algorithms/detail/closest_points/interface.hpp
  include/boost/geometry/algorithms/detail/closest_points/linear_or_areal_to_areal.hpp
  include/boost/geometry/algorithms/detail/closest_points/linear_to_linear.hpp
  include/boost/geometry/algorithms/detail/closest_points/multipoint_to_geometry.hpp
  include/boost/geometry/algorithms/detail/closest_points/range_to_geometry_rtree.hpp
  include/boost/geometry/algorithms/detail/closest_points/segment_to_segment.hpp
  include/boost/geometry/algorithms/detail/closest_points/utilities.hpp
  include/boost/geometry/strategies/cartesian/closest_points_pt_seg.hpp
  include/boost/geometry/strategies/closest_points/geographic.hpp
  include/boost/geometry/strategies/closest_points/spherical.hpp
  include/boost/geometry/strategies/geographic/closest_points_pt_seg.hpp
  include/boost/geometry/strategies/geographic/distance_cross_track.hpp
  include/boost/geometry/strategies/spherical/closest_points_pt_seg.hpp
  include/boost/geometry/strategies/spherical/distance_cross_track.hpp
  test/algorithms/closest_points/Jamfile.v2
  test/algorithms/closest_points/ar_ar.cpp
  test/algorithms/closest_points/common.hpp
  test/algorithms/closest_points/empty_geometry.hpp
  test/algorithms/closest_points/l_ar.cpp
  test/algorithms/closest_points/l_l.cpp
  test/algorithms/closest_points/pl_ar.cpp
  test/algorithms/closest_points/pl_l.cpp
  test/algorithms/closest_points/pl_pl.cpp
Labels: enhancement, documentation

#959 Propagate umbrella strategy in buffer and overlay.
  include/boost/geometry/algorithms/detail/buffer/buffered_piece_collection.hpp
  include/boost/geometry/algorithms/detail/buffer/piece_border.hpp
  include/boost/geometry/algorithms/detail/buffer/turn_in_piece_visitor.hpp
  include/boost/geometry/algorithms/detail/overlay/get_distance_measure.hpp
  include/boost/geometry/algorithms/detail/overlay/get_turn_info.hpp
  include/boost/geometry/strategies/buffer/cartesian.hpp
  include/boost/geometry/strategies/buffer/geographic.hpp
  include/boost/geometry/strategies/buffer/spherical.hpp
  test/algorithms/buffer/buffer_multi_point.cpp
  test/algorithms/buffer/buffer_piece_border.cpp
  test/algorithms/buffer/test_buffer_geo.hpp
Labels: bug

#963 Fix rtree elements count check in serialization/load.
  include/boost/geometry/index/detail/serialization.hpp
Labels: bug

#967 Fix closest points test
  test/algorithms/closest_points/common.hpp
  test/algorithms/closest_points/pl_l.cpp
Labels: tests

#968 Fix dissolve and side_robust test
  extensions/test/algorithms/dissolve.cpp
  extensions/test/triangulation/side_robust.cpp
  include/boost/geometry/extensions/algorithms/detail/overlay/dissolver.hpp
  include/boost/geometry/extensions/algorithms/dissolve.hpp
Labels: bug, tests, extensions

#966 Fix simplify for open rings and improve it
  include/boost/geometry/algorithms/simplify.hpp
  test/algorithms/simplify.cpp
Labels: bug
