Repository boostorg/geometry, pull requests merged in 2022-06, with the labels that each got.

#1010 Allow start for self-turns for difference overlay operations
  include/boost/geometry/algorithms/detail/overlay/handle_colocations.hpp
  test/algorithms/overlay/multi_overlay_cases.hpp
  test/algorithms/set_operations/difference/difference_multi.cpp
Labels: bug

#1014 Add missing projections and fixing existing ones
  include/boost/geometry/srs/projections/dpar.hpp
  include/boost/geometry/srs/projections/epsg.hpp
  include/boost/geometry/srs/projections/epsg_params.hpp
  include/boost/geometry/srs/projections/epsg_traits.hpp
  include/boost/geometry/srs/projections/factory.hpp
  include/boost/geometry/srs/projections/impl/pj_datum_set.hpp
  include/boost/geometry/srs/projections/impl/pj_fwd.hpp
  include/boost/geometry/srs/projections/impl/pj_generic_inverse.hpp
  include/boost/geometry/srs/projections/impl/pj_init.hpp
  include/boost/geometry/srs/projections/impl/pj_inv.hpp
  include/boost/geometry/srs/projections/impl/projects.hpp
  include/boost/geometry/srs/projections/par_data.hpp
  include/boost/geometry/srs/projections/proj/cass.hpp
  include/boost/geometry/srs/projections/proj/col_urban.hpp
  include/boost/geometry/srs/projections/proj/krovak.hpp
  include/boost/geometry/srs/projections/proj/omerc.hpp
  include/boost/geometry/srs/projections/proj/stere.hpp
  include/boost/geometry/srs/projections/spar.hpp
  test/srs/projection_epsg.cpp
  test/srs/projection_selftest_cases.hpp
  test/srs/projections.cpp
Labels: enhancement, tests

#994 [side] added side_rounded_input and robustness test
  include/boost/geometry/strategies/cartesian/side_rounded_input.hpp
  include/boost/geometry/strategy/cartesian/side_by_triangle.hpp
  test/strategies/Jamfile
  test/strategies/side_rounded_input.cpp
Labels: tests

#1013 Fixes warning with -Wduplicated-branches in overlay for union (issue #443).
  include/boost/geometry/algorithms/detail/overlay/overlay.hpp
Labels: warning

#1024 Allow different input and output types in simplify
  include/boost/geometry/algorithms/simplify.hpp
  test/algorithms/simplify.cpp
Labels: enhancement
