Repository boostorg/geometry, pull requests merged in 2022-02, with the labels that each got.

#972 [fix] for integer coordinates, segment intersection now rounds to nearest point
  include/boost/geometry/algorithms/detail/overlay/overlay.hpp
  include/boost/geometry/core/config.hpp
  include/boost/geometry/strategies/cartesian/intersection.hpp
  include/boost/geometry/util/math.hpp
  test/algorithms/overlay/multi_overlay_cases.hpp
  test/algorithms/overlay/overlay.cpp
  test/algorithms/set_operations/difference/difference.cpp
  test/algorithms/set_operations/difference/difference_areal_linear.cpp
  test/algorithms/set_operations/difference/difference_multi.cpp
  test/algorithms/set_operations/difference/difference_multi_spike.cpp
  test/util/Jamfile
  test/util/math_divide.cpp
Labels: bug

#973 Test boxes intersection in separate file and add geographic tests.
  test/algorithms/set_operations/intersection/Jamfile
  test/algorithms/set_operations/intersection/intersection.cpp
  test/algorithms/set_operations/intersection/intersection_box.cpp
Labels: tests

#974 Fix spheroidal normalization utilities for NaN coordinates
  include/boost/geometry/util/normalize_spheroidal_box_coordinates.hpp
  include/boost/geometry/util/normalize_spheroidal_coordinates.hpp
  test/util/Jamfile
  test/util/math_normalize_spheroidal.cpp
Labels: bug

#961 Add Web Mercator projection
  include/boost/geometry/srs/projections/dpar.hpp
  include/boost/geometry/srs/projections/epsg.hpp
  include/boost/geometry/srs/projections/epsg_traits.hpp
  include/boost/geometry/srs/projections/proj/merc.hpp
  include/boost/geometry/srs/projections/spar.hpp
  test/srs/projections.cpp
  test/srs/projections_static.cpp
Labels: enhancement

#936 Fix envelope of polygon containing pole.
  include/boost/geometry/algorithms/detail/disjoint/segment_box.hpp
  include/boost/geometry/algorithms/detail/envelope/areal.hpp
  include/boost/geometry/algorithms/detail/envelope/geometry_collection.hpp
  include/boost/geometry/algorithms/detail/envelope/range.hpp
  include/boost/geometry/strategies/envelope/cartesian.hpp
  include/boost/geometry/strategies/envelope/geographic.hpp
  include/boost/geometry/strategies/envelope/spherical.hpp
  include/boost/geometry/strategies/spherical/distance_segment_box.hpp
  include/boost/geometry/strategy/cartesian/envelope_boxes.hpp
  include/boost/geometry/strategy/cartesian/envelope_range.hpp
  include/boost/geometry/strategy/geographic/envelope_range.hpp
  include/boost/geometry/strategy/spherical/envelope_boxes.hpp
  include/boost/geometry/strategy/spherical/envelope_range.hpp
  include/boost/geometry/views/closeable_view.hpp
  include/boost/geometry/views/detail/closed_clockwise_view.hpp
  include/boost/geometry/views/reversible_view.hpp
  test/algorithms/envelope_expand/envelope_on_spheroid.cpp
Labels: bug

#976 [test] fix coordinates to make the polygon invalid as designed
  test/algorithms/Jamfile
  test/algorithms/is_valid.cpp
  test/algorithms/overlay/traverse.cpp
  test/policies/rescale_policy.cpp
  test/robustness/overlay/areal_areal/intersection_pies.cpp
  test/robustness/overlay/areal_areal/intersection_stars.cpp
  test/robustness/overlay/areal_areal/intersects.cpp
  test/robustness/overlay/areal_areal/random_ellipses_stars.cpp
  test/robustness/overlay/areal_areal/recursive_polygons.cpp
  test/robustness/overlay/areal_areal/star_comb.cpp
  test/robustness/overlay/buffer/recursive_polygons_buffer.cpp
Labels: tests

#979 Promote content and margin result to double instead of long double
  include/boost/geometry/index/detail/algorithms/content.hpp
  include/boost/geometry/index/detail/algorithms/margin.hpp
Labels: bug

#977 [major change] change the default, disable rescaling by default
  doc/release_notes.qbk
  include/boost/geometry/core/config.hpp
  include/boost/geometry/strategy/spherical/envelope_range.hpp
  test/algorithms/set_operations/union/union_other_types.cpp
  test/robustness/overlay/areal_areal/general_intersection_precision.cpp
  test/robustness/overlay/areal_areal/interior_triangles.cpp
  test/robustness/overlay/areal_areal/intersection_pies.cpp
  test/robustness/overlay/areal_areal/intersection_stars.cpp
  test/robustness/overlay/areal_areal/intersects.cpp
  test/robustness/overlay/areal_areal/random_ellipses_stars.cpp
  test/robustness/overlay/areal_areal/recursive_polygons.cpp
  test/robustness/overlay/areal_areal/star_comb.cpp
  test/robustness/overlay/buffer/recursive_polygons_buffer.cpp
Labels: enhancement
