Repository boostorg/geometry, pull requests merged in 2022-04, with the labels that each got.

#978 [srs] Accurate methods for ellipsoidal tmerc
  include/boost/geometry/srs/projections/proj/tmerc.hpp
  test/srs/projection_interface_d.cpp
  test/srs/projection_interface_s.cpp
  test/srs/projection_selftest_cases.hpp
  test/srs/transformation_interface.cpp
Labels: enhancement, tests

#990 Check return value from fe_segment_range_with_closure in for_each.hpp
  include/boost/geometry/algorithms/for_each.hpp
Labels: bug

#991 Fix c++20 compilation errors related to conditional expression
  include/boost/geometry/policies/robustness/segment_ratio.hpp
Labels: bug

#986 Fix const disjoint
  include/boost/geometry/algorithms/detail/disjoint/areal_areal.hpp
  include/boost/geometry/algorithms/detail/disjoint/linear_areal.hpp
  include/boost/geometry/algorithms/detail/disjoint/linear_linear.hpp
  include/boost/geometry/algorithms/detail/overlay/get_turns.hpp
  include/boost/geometry/algorithms/detail/overlay/linear_linear.hpp
  include/boost/geometry/algorithms/detail/relate/areal_areal.hpp
  include/boost/geometry/algorithms/detail/relate/boundary_checker.hpp
  include/boost/geometry/algorithms/detail/relate/follow_helpers.hpp
  include/boost/geometry/algorithms/detail/relate/linear_areal.hpp
  include/boost/geometry/algorithms/detail/relate/linear_linear.hpp
  include/boost/geometry/algorithms/detail/relate/turns.hpp
  include/boost/geometry/algorithms/detail/touches/implementation.hpp
  test/algorithms/overlay/test_get_turns.hpp
  test/algorithms/relate/Jamfile
  test/algorithms/relate/relate_const.cpp
  test/algorithms/set_operations/check_turn_less.hpp
  test/algorithms/set_operations/test_get_turns_ll_invariance.hpp
  test/robustness/overlay/areal_areal/interior_triangles.cpp
  test/test_geometries/const_point.hpp
  test/to_svg.hpp
Labels: bug

#992 [test][disjoint] Add tests for box vs open ring.
  test/algorithms/disjoint/disjoint_point_box_geometry.cpp
Labels: bug, tests
