Repository boostorg/geometry, pull requests merged in 2022-05, with the labels that each got.

#999 Change 4 broken postgis.org links to postgis.net
  doc/reference/algorithms/covered_by.qbk
  doc/reference/algorithms/densify.qbk
  doc/reference/algorithms/perimeter.qbk
  doc/reference/algorithms/simplify.qbk
Labels: documentation

#1005 Fix auto return in distance_cross_track strategy
  include/boost/geometry/strategies/geographic/distance_cross_track.hpp
Labels: bug

#996 [relate] Refactor relate utilities and implementation.
  include/boost/geometry/algorithms/detail/overlay/follow.hpp
  include/boost/geometry/algorithms/detail/overlay/linear_linear.hpp
  include/boost/geometry/algorithms/detail/relate/areal_areal.hpp
  include/boost/geometry/algorithms/detail/relate/boundary_checker.hpp
  include/boost/geometry/algorithms/detail/relate/follow_helpers.hpp
  include/boost/geometry/algorithms/detail/relate/implementation.hpp
  include/boost/geometry/algorithms/detail/relate/linear_areal.hpp
  include/boost/geometry/algorithms/detail/relate/linear_linear.hpp
  include/boost/geometry/algorithms/detail/relate/turns.hpp
  test/algorithms/set_operations/check_turn_less.hpp
  test/algorithms/set_operations/test_get_turns_ll_invariance.hpp
Labels: enhancement

#1003 Fix line_interpolate termination condition for single points.
  include/boost/geometry/algorithms/line_interpolate.hpp
Labels: bug

#997 Add support for GeometryCollection in difference()
  include/boost/geometry/algorithms/detail/make_rtree.hpp
  include/boost/geometry/algorithms/difference.hpp
  include/boost/geometry/views/detail/geometry_collection_view.hpp
  test/algorithms/set_operations/difference/Jamfile
  test/algorithms/set_operations/difference/difference_gc.cpp
Labels: enhancement
