Repository boostorg/geometry, pull requests merged in 2022-12, with the labels that each got.

#1080 [index] Fix dangling references when Indexable is returned by value by IndexableGetter.
  include/boost/geometry/index/detail/rtree/linear/redistribute_elements.hpp
  include/boost/geometry/index/detail/rtree/rstar/redistribute_elements.hpp
  include/boost/geometry/index/rtree.hpp
Labels: bug

#1098 [doc] Explain output range of azimuth algorithm.
  doc/html/index.html
  doc/reference/algorithms/azimuth.qbk
Labels: documentation

#1099 Update release notes for 1.81
  doc/release_notes.qbk
  extensions/meta/libraries.json
  index/meta/libraries.json
  meta/libraries.json
Labels: documentation

#1101 [buffer] add spheroid to buffer strategies as an optional constructor parameter
  include/boost/geometry/strategies/geographic/buffer_end_round.hpp
  include/boost/geometry/strategies/geographic/buffer_join_miter.hpp
  include/boost/geometry/strategies/geographic/buffer_join_round.hpp
  include/boost/geometry/strategies/geographic/buffer_point_circle.hpp
  include/boost/geometry/strategies/geographic/buffer_side_straight.hpp
  test/algorithms/buffer/Jamfile
  test/algorithms/buffer/buffer_geo_spheroid.cpp
Labels: enhancement
