Repository boostorg/geometry, pull requests merged in 2023-07, with the labels that each got.

#1157 [algorithms] Check const Ring concept in calculate_point_order
  include/boost/geometry/algorithms/detail/calculate_point_order.hpp
Labels: bug

#1160 Fix Visual Studio warnings
  include/boost/geometry/algorithms/detail/buffer/piece_border.hpp
  include/boost/geometry/algorithms/detail/convex_hull/interface.hpp
  include/boost/geometry/algorithms/detail/overlay/handle_self_turns.hpp
  include/boost/geometry/algorithms/detail/overlay/pointlike_pointlike.hpp
  include/boost/geometry/algorithms/detail/relate/implementation_gc.hpp
  include/boost/geometry/algorithms/detail/relate/linear_areal.hpp
  include/boost/geometry/algorithms/detail/sweep.hpp
  include/boost/geometry/algorithms/detail/within/multi_point.hpp
  include/boost/geometry/algorithms/simplify.hpp
  include/boost/geometry/formulas/area_formulas.hpp
  include/boost/geometry/formulas/differential_quantities.hpp
  include/boost/geometry/formulas/gnomonic_intersection.hpp
  include/boost/geometry/formulas/karney_inverse.hpp
  include/boost/geometry/formulas/meridian_direct.hpp
  include/boost/geometry/formulas/meridian_inverse.hpp
  include/boost/geometry/formulas/sjoberg_intersection.hpp
  include/boost/geometry/srs/projections/impl/pj_init.hpp
  include/boost/geometry/srs/projections/impl/pj_transform.hpp
  include/boost/geometry/srs/projections/proj/tmerc.hpp
  include/boost/geometry/strategies/cartesian/buffer_join_round.hpp
  include/boost/geometry/strategies/cartesian/intersection.hpp
  include/boost/geometry/strategies/cartesian/turn_in_ring_winding.hpp
  include/boost/geometry/strategies/geographic/buffer_join_round.hpp
  include/boost/geometry/strategies/geographic/distance_cross_track.hpp
  include/boost/geometry/util/precise_math.hpp
  include/boost/geometry/util/series_expansion.hpp
  test/algorithms/set_operations/difference/test_difference.hpp
  test/algorithms/set_operations/intersection/test_intersection.hpp
  test/algorithms/set_operations/intersection/test_intersection_linear_linear.hpp
  test/geometries/boost_polygon.cpp
  test/geometries/custom_non_copiable/helper_functions.hpp
  test/iterators/test_iterator_common.hpp
  test/strategies/buffer_join_geo.cpp
  test/util/select_most_precise.cpp
Labels: warning

#1168 Add if constexpr macro and replace condition macro.
  include/boost/geometry/algorithms/densify.hpp
  include/boost/geometry/algorithms/detail/buffer/buffer_inserter.hpp
  include/boost/geometry/algorithms/detail/is_valid/linear.hpp
  include/boost/geometry/algorithms/detail/is_valid/multipolygon.hpp
  include/boost/geometry/algorithms/detail/is_valid/polygon.hpp
  include/boost/geometry/io/wkt/write.hpp
  include/boost/geometry/policies/is_valid/failing_reason_policy.hpp
  include/boost/geometry/util/constexpr.hpp
Labels: enhancement

#1172 Update rescaling deprecation warning message
  include/boost/geometry/core/config.hpp
Labels: warning

#1177 [within] Fix the case when a segment has as an endpoint a pole
  include/boost/geometry/strategies/spherical/point_in_poly_winding.hpp
  test/algorithms/covered_by/covered_by_sph_geo.cpp
  test/algorithms/within/within_pointlike_geometry.cpp
Labels: bug
