Repository boostorg/geometry, pull requests merged in 2024-11, with the labels that each got.

#1335 chore: replace typename coordinate_system with coordinate_system_t
  include/boost/geometry/algorithms/detail/envelope/intersects_antimeridian.hpp
  include/boost/geometry/algorithms/detail/equals/collect_vectors.hpp
  include/boost/geometry/algorithms/detail/gc_make_rtree.hpp
  include/boost/geometry/algorithms/detail/overlay/pointlike_areal.hpp
  include/boost/geometry/algorithms/detail/sections/section_functions.hpp
  include/boost/geometry/algorithms/detail/sections/sectionalize.hpp
  include/boost/geometry/algorithms/detail/touches/implementation.hpp
  include/boost/geometry/algorithms/merge_elements.hpp
  include/boost/geometry/core/coordinate_system.hpp
  include/boost/geometry/core/radian_access.hpp
  include/boost/geometry/formulas/geographic.hpp
  include/boost/geometry/geometries/adapted/boost_polygon/point.hpp
  include/boost/geometry/geometries/concepts/point_concept.hpp
  include/boost/geometry/index/rtree.hpp
  include/boost/geometry/srs/transformation.hpp
  include/boost/geometry/strategies/cartesian/closest_points_pt_seg.hpp
  include/boost/geometry/strategies/cartesian/distance_projected_point_ax.hpp
  include/boost/geometry/strategies/geographic/closest_points_pt_seg.hpp
  include/boost/geometry/strategies/spherical/closest_points_pt_seg.hpp
  test/algorithms/envelope_expand/envelope_on_spheroid.cpp
  test/algorithms/envelope_expand/expand_on_spheroid.cpp
  test/algorithms/similarity/discrete_frechet_distance.cpp
  test/algorithms/similarity/discrete_hausdorff_distance.cpp
  test/concepts/point_concept_checker.cpp
  test/concepts/point_well_formed_traits.cpp
  test/concepts/point_with_incorrect_dimension.cpp
  test/concepts/point_without_coordinate_type.cpp
  test/concepts/point_without_dimension.cpp
  test/concepts/point_without_getter.cpp
  test/concepts/point_without_setter.cpp
  test/geometries/concepts/check.cpp
  test/test_common/test_point.hpp
  test/test_common/with_pointer.hpp
Labels: refactoring

#1334 Fix extensions
  extensions/example/gis/Jamfile
  extensions/example/gis/latlong/Jamfile
  extensions/example/gis/latlong/distance_example.cpp
  extensions/example/gis/latlong/point_ll_example.cpp
  extensions/example/gis/projections/Jamfile
  extensions/example/gis/projections/p01_projection_example.cpp
  extensions/example/gis/projections/p02_projfactory_example.cpp
  extensions/example/gis/projections/p03_projmap_example.cpp
  extensions/example/gis/projections/p04_example.cpp
  extensions/example/gis/projections/p05_example.cpp
  include/boost/geometry/extensions/nsphere/geometries/nsphere.hpp
  include/boost/geometry/formulas/meridian_inverse.hpp
  include/boost/geometry/formulas/vincenty_inverse.hpp
  test/robustness/overlay/linear_areal/recursive_polygons_linear_areal.cpp
Labels: tests

#1336 chore: modernize ring and related types to ring_t and related
  include/boost/geometry/algorithms/convert.hpp
  include/boost/geometry/algorithms/detail/buffer/buffer_inserter.hpp
  include/boost/geometry/algorithms/detail/buffer/buffered_ring.hpp
  include/boost/geometry/algorithms/detail/disjoint/linear_areal.hpp
  include/boost/geometry/algorithms/detail/distance/point_to_geometry.hpp
  include/boost/geometry/algorithms/detail/envelope/areal.hpp
  include/boost/geometry/algorithms/detail/equals/collect_vectors.hpp
  include/boost/geometry/algorithms/detail/extreme_points.hpp
  include/boost/geometry/algorithms/detail/is_valid/polygon.hpp
  include/boost/geometry/algorithms/detail/overlay/copy_segment_point.hpp
  include/boost/geometry/algorithms/detail/overlay/get_ring.hpp
  include/boost/geometry/algorithms/detail/overlay/get_turns.hpp
  include/boost/geometry/algorithms/detail/overlay/overlay.hpp
  include/boost/geometry/algorithms/detail/overlay/select_rings.hpp
  include/boost/geometry/algorithms/detail/relate/linear_areal.hpp
  include/boost/geometry/algorithms/detail/sections/range_by_section.hpp
  include/boost/geometry/algorithms/detail/sub_range.hpp
  include/boost/geometry/algorithms/detail/within/point_in_geometry.hpp
  include/boost/geometry/algorithms/perimeter.hpp
  include/boost/geometry/core/exterior_ring.hpp
  include/boost/geometry/core/interior_rings.hpp
  include/boost/geometry/core/interior_type.hpp
  include/boost/geometry/core/point_type.hpp
  include/boost/geometry/core/ring_type.hpp
  include/boost/geometry/io/dsv/write.hpp
  include/boost/geometry/io/svg/write.hpp
  include/boost/geometry/io/wkt/read.hpp
  include/boost/geometry/io/wkt/write.hpp
  include/boost/geometry/iterators/detail/point_iterator/inner_range_type.hpp
  include/boost/geometry/views/detail/boundary_view/implementation.hpp
  test/algorithms/distance/test_distance_common.hpp
  test/algorithms/overlay/dissolver.cpp
  test/algorithms/overlay/split_rings.cpp
  test/core/ring.cpp
  test/robustness/common/make_square_polygon.hpp
Labels: refactoring

#1338 chore: replace typedef with using in overlay
  include/boost/geometry/algorithms/detail/buffer/buffer_inserter.hpp
  include/boost/geometry/algorithms/detail/buffer/buffer_policies.hpp
  include/boost/geometry/algorithms/detail/buffer/buffered_piece_collection.hpp
  include/boost/geometry/algorithms/detail/buffer/buffered_ring.hpp
  include/boost/geometry/algorithms/detail/buffer/get_piece_turns.hpp
  include/boost/geometry/algorithms/detail/buffer/implementation.hpp
  include/boost/geometry/algorithms/detail/buffer/piece_border.hpp
  include/boost/geometry/algorithms/detail/intersection/areal_areal.hpp
  include/boost/geometry/algorithms/detail/intersection/interface.hpp
  include/boost/geometry/algorithms/detail/overlay/add_rings.hpp
  include/boost/geometry/algorithms/detail/overlay/assign_parents.hpp
  include/boost/geometry/algorithms/detail/overlay/backtrack_check_si.hpp
  include/boost/geometry/algorithms/detail/overlay/clip_linestring.hpp
  include/boost/geometry/algorithms/detail/overlay/follow.hpp
  include/boost/geometry/algorithms/detail/overlay/follow_linear_linear.hpp
  include/boost/geometry/algorithms/detail/overlay/get_intersection_points.hpp
  include/boost/geometry/algorithms/detail/overlay/get_turn_info.hpp
  include/boost/geometry/algorithms/detail/overlay/get_turn_info_for_endpoint.hpp
  include/boost/geometry/algorithms/detail/overlay/get_turn_info_helpers.hpp
  include/boost/geometry/algorithms/detail/overlay/get_turn_info_la.hpp
  include/boost/geometry/algorithms/detail/overlay/get_turn_info_ll.hpp
  include/boost/geometry/algorithms/detail/overlay/get_turns.hpp
  include/boost/geometry/algorithms/detail/overlay/handle_colocations.hpp
  include/boost/geometry/algorithms/detail/overlay/intersection_insert.hpp
  include/boost/geometry/algorithms/detail/overlay/less_by_segment_ratio.hpp
  include/boost/geometry/algorithms/detail/overlay/linear_linear.hpp
  include/boost/geometry/algorithms/detail/overlay/needs_self_turns.hpp
  include/boost/geometry/algorithms/detail/overlay/overlay.hpp
  include/boost/geometry/algorithms/detail/overlay/pointlike_areal.hpp
  include/boost/geometry/algorithms/detail/overlay/pointlike_linear.hpp
  include/boost/geometry/algorithms/detail/overlay/pointlike_pointlike.hpp
  include/boost/geometry/algorithms/detail/overlay/range_in_geometry.hpp
  include/boost/geometry/algorithms/detail/overlay/ring_properties.hpp
  include/boost/geometry/algorithms/detail/overlay/select_rings.hpp
  include/boost/geometry/algorithms/detail/overlay/traversal_ring_creator.hpp
  include/boost/geometry/algorithms/detail/overlay/turn_info.hpp
Labels: refactoring

#1346 fix: add condition to handle_imperfect_touch
  doc/release_notes.qbk
  include/boost/geometry/algorithms/detail/overlay/get_turn_info.hpp
  include/boost/geometry/algorithms/detail/overlay/get_turn_info_helpers.hpp
  test/algorithms/overlay/multi_overlay_cases.hpp
  test/algorithms/overlay/overlay_cases.hpp
  test/algorithms/set_operations/difference/difference.cpp
  test/algorithms/set_operations/difference/difference_multi.cpp
  test/algorithms/set_operations/intersection/intersection.cpp
  test/algorithms/set_operations/intersection/intersection_multi.cpp
  test/algorithms/set_operations/union/union.cpp
  test/algorithms/set_operations/union/union_multi.cpp
Labels: bug
